import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/widgets/ui";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { cn } from "@/lib/utils";
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={cn(
            "relative flex min-h-screen w-full flex-col justify-center items-center overflow-x-hidden scroll-smooth bg-background font-sans antialiased",
            geistMono.variable
          )}
        >
          <Header />
          <main className="flex-1">{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
